# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Gallery'
pod 'InstantSearchClient'
pod 'EmptyDataSet-Swift'
pod 'NVActivityIndicatorView/AppExtension'
pod 'JGProgressHUD'
pod 'PayPal-iOS-SDK'


  # Pods for MarketMall

  target 'MarketMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarketMallUITests' do
    # Pods for testing
  end

end
